Issues
softeria-test/umur-test pull request #3
Opened 2022-11-07 11:42 UTC by UmurErgenay

I migrated to yarn 3.x.x version, and added the ".yarn" folder to gitignore.

resolves #1

2022-11-07 11:47 UTC, UmurErgenay commented
[new yarn.lock file generated] as well

2022-11-07 11:53 UTC, emreliman reviewed
✔

2022-11-08 08:01 UTC, ismailarilik requested changes

2022-11-08 08:01 UTC, ismailarilik commented on src/components/TableComponent.vue
>  }
It seems that this doesn't belong here.

2022-11-08 08:01 UTC, ismailarilik commented on src/table.json
>                null,
It seems that this doesn't belong here.

2022-11-08 11:10 UTC, merged